spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com//jostery-chalamila/git-config-repo.git
          clone-on-start: true
          default-label: main
        bootstrap: true
      enabled: true
   
  application:
    Name: Config-Server-Test
    City: Dar es salaam
    Country: Tanzania
    Code: 255
